[package]
name = "ryoiki"
version = "0.1.9"
edition = "2021"
authors = ["Praveensenpai <pvnt20@gmail.com>"]
description = "Aesthetic, zero-clutter Ubuntu server provisioning orchestrator"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
ratatui = "0.29"
crossterm = "0.28"
indicatif = "0.17"
colored = "2.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[lints.rust]
unused = "deny"
dead_code = "deny"
warnings = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cognitive_complexity = "warn"
too_many_arguments = "deny"
unwrap_used = "deny"
expect_used = "deny"
